drop table if exists member CASCADE;

-- 테이블 만들기
create table member
    {
    id  bigint generated by as identify,
    name varchar(255),
    primary key(id)
    };

-- 멤버 테이블에 'spring' name을 가진 member 넣기
insert into member(name) values('spring')